# 1. create a network with docker network create NETWORKNAME
# 2. Create letsencrypt directory for acme.json ie /docker/letsencrypt directory or somewhere else mkdir -p /docker/letsencrypt
# 3. I configured http -> https redirect
# cat docker-compose.yml

version: '3.3'

services:
  traefik2:
    image: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=MYEMAIL@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/letsencrypt:/letsencrypt
    container_name: traefik

  canvas_blocks:
    container_name: canvas_blocks
    image: nginx
    restart: always
    networks:
      - nginx
    volumes:
     - ./canvas-blocks/dist:/usr/share/nginx/html
    ports:
     - "8080:80"
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.http.routers.canvas_blocks.rule=Host(`canvas-blocks.andreabardinet.fr`)
      - traefik.http.routers.canvas_blocks.entrypoints=websecure
      - traefik.http.routers.canvas_blocks.tls=true
      - traefik.http.routers.canvas_blocks.tls.certresolver=myresolver
    environment:
     - NGINX_HOST=andreabardinet.fr
     - NGINX_PORT=80

  portfolio:
    container_name: portfolio
    image: nginx
    restart: always
    networks:
      - nginx
    volumes:
     - ./portfolio/dist:/usr/share/nginx/html
    ports:
     - "8081:80"
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.http.routers.portfolio.rule=Host(`portfolio.andreabardinet.fr`,`andreabardinet.fr`)
      - traefik.http.routers.portfolio.entrypoints=websecure
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.routers.portfolio.tls.certresolver=myresolver
    environment:
     - NGINX_HOST=andreabardinet.fr
     - NGINX_PORT=80



networks:
  nginx:
    external: true